title: Elias Farnleitner
url: ""
baseurl: "efarnleitner.github.io"


remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "resume.pdf"
